_BASE_: "Base-RCNN-FPN.yaml"

MODEL:
  #WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_SIAMESE_HEAD:
    PROJECTOR_TYPE: "residual"
    N_RESIDUAL_LAYERS: 4
    HARD_NEGATIVE_MINING:
      ENABLE: True
      NUM_NEGATIVES: 64
    USE_CROSS_BATCH_NEGATIVES: True
    IN_FEATURES: ["p3"]
    SHARE_PROJECTION: True
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 64
    POSITIVE_FRACTION: 0.1

SOLVER:
  STEPS: (200000, 400000)
  MAX_ITER: 1000000
  IMS_PER_BATCH: 16

INPUT:
  TRANSFORM_VISUAL_CROP: True
  ENABLE_RANDOM_ROTATION_VISUAL_CROP: True
  ROTATION_ANGLES: [-120, 120]
  ENABLE_RANDOM_BRIGHTNESS: True

DATALOADER:
  NUM_WORKERS: 8

DATASETS:
  TRAIN: ("visual_query_clean_aug_train", )
  TEST: ("visual_query_clean_val", )